import WebSocket from 'file:///C:/Users/24645/.workbuddy/binaries/node/workspace/node_modules/ws/index.js';
import { appendFileSync, unlinkSync } from 'fs';
const LOGF = new URL('./diag3-out.log', import.meta.url);
try { unlinkSync(LOGF); } catch {}
const t0 = Date.now();
const log = (...a) => { try { appendFileSync(LOGF, (Date.now() - t0) + 'ms ' + a.join(' ') + '\n'); } catch {} };
setTimeout(() => { log('WATCHDOG'); process.exit(2); }, 25000);
const tab = await (await fetch('http://127.0.0.1:9222/json/new?about:blank', { method: 'PUT' })).json();
const ws = new WebSocket(tab.webSocketDebuggerUrl);
await new Promise((r, j) => { ws.on('open', r); ws.on('error', j); });
log('ws open');
let id = 0;
const penders = new Map();
ws.on('message', (d) => { const m = JSON.parse(d); if (m.id && penders.has(m.id)) { penders.get(m.id)(m); penders.delete(m.id); } });
const s = (m, pp = {}) => new Promise((r) => { const i = ++id; penders.set(i, r); ws.send(JSON.stringify({ id: i, method: m, params: pp })); });
await s('Page.enable');
await s('Emulation.setDeviceMetricsOverride', { width: 390, height: 844, deviceScaleFactor: 2, mobile: true });
await s('Page.navigate', { url: 'http://127.0.0.1:4321/blog/' });
await new Promise((r) => setTimeout(r, 4000));
const probe = `(async()=>{const r={};
  r.href=location.href; r.title=document.title;
  r.header=!!document.querySelector('.site-header');
  r.toggle=!!document.querySelector('[data-mnav-toggle]');
  r.bodyLen=document.body?document.body.innerHTML.length:-1;
  r.head0=document.head?document.head.innerHTML.slice(0,120):'(no head)';
  const fr=document.querySelector('astro-island');
  return JSON.stringify(r);})()`;
const res = await s('Runtime.evaluate', { expression: probe, returnByValue: true, awaitPromise: true });
log('PROBE', res.result?.result?.value ?? JSON.stringify(res).slice(0, 300));
await fetch('http://127.0.0.1:9222/json/close/' + tab.id);
process.exit(0);
